name: Java CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        java: [8, 11, 17, 21]
        experimental: [false]
        include:
          - java: 23
            experimental: true
            os: ubuntu-latest
          - java: 24-ea
            experimental: true
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - uses: actions/cache@v4.1.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn --errors --show-version --batch-mode --no-transfer-progress -Ddoclint=all

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_AUTH_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=TAOUBI-123_commons-lang \
          -Dsonar.organization=lang \
          -Dsonar.host.url=https://sonarcloud.io

